language: zh
pipeline:
- name: zh_rasa.TFNLUClassifier
  epochs: 10
  encoder_path: https://code.aliyun.com/qhduan/bert_part/raw/508f4beacff09890d60fbaf273dff6c0d4932863/roberta_wwm_1.tar.gz
- name: zh_rasa.TFNLUExtractor
  epochs: 30
  encoder_path: https://code.aliyun.com/qhduan/bert_part/raw/508f4beacff09890d60fbaf273dff6c0d4932863/roberta_wwm_1.tar.gz
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
  constrain_similarities: true
  model_confidence: linear_norm
